version: '3'

volumes:
  keycloak_data:
  mysql_database_user:
  mysql_database_destiny:
  mysql_database_book:
  mysql_database_fly:
  mysql_database_accommodation:

services:
  mysql_database_user:
    image: mysql:8.0.34
    volumes:
      - mysql_database_user:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_destiny:
    image: mysql:8.0.34
    volumes:
      - mysql_database_destiny:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_fly:
      image: mysql:8.0.34
      volumes:
        - mysql_database_fly:/var/lib/mysql
      environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=root1234
        - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_book:
    image: mysql:8.0.34
    volumes:
      - mysql_database_book:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  mysql_database_accommodation:
    image: mysql:8.0.34
    volumes:
      - mysql_database_accommodation:/var/lib/mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root1234
      - MYSQL_ROOT_PASSWORD=root1234

  eureka-server:
    image: bib_eureka
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  gateway:
    image: bib_gateway
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      spring.security.oauth2.resourceserver.jwt.issuer-uri=http: //keycloak:8080/realms/unitravel-auth
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http: //keycloak:8080/realms/unitravel-auth/protocol/openid-connect/certs
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    links:
      - eureka-server


  accommodation:
    image: bib_accommodation
    build: ./accommodation-service
    restart: always
    depends_on:
      - mysql_database_accommodation
      - rabbitmq
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_accommodation:3306/accommodation?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: 12345
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  book:
    image: bib_book
    build: ./book-service
    restart: always
    depends_on:
      - mysql_database_book
      - rabbitmq
      - eureka-server
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_book:3306/book?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: 12345
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  destiny:
    image: bib_destiny
    build: ./destiny-service
    restart: always
    depends_on:
      - mysql_database_destiny
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_destiny:3306/destiny?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: 12345
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  fly:
    image: bib_fly
    build: ./fly-service
    restart: always
    depends_on:
      - mysql_database_fly
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_fly:3306/fly?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: 12345
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  user:
    image: bib_user
    build: ./user-service
    restart: always
    depends_on:
      - mysql_database_user
      - eureka-server
      - rabbitmq
    environment:
      spring.datasource.url: jdbc:mysql://mysql_database_user:3306/user?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: 12345
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.rabbitmq.host: rabbitmq

  authentication:
    image: bib_authentication
    build: ./authentication-service
    restart: always
    depends_on:
      - eureka-server
      - keycloak
      - gateway
    environment:
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:9090/realms/unitravel-auth
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:9090/realms/unitravel-auth/protocol/openid-connect/certs
      keycloack.admin-url: http://keycloak:9090/admin/realms/unitravel-auth
    links:
      - eureka-server



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    ports:
      - "9090:9090"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak_data:/opt/keycloak/data/
    command: [ "start-dev", "--http-port=9090" ]